CREATE DATABASE IF NOT EXISTS `gundam` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `gundam`;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wishlists (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) NOT NULL,
  model_id VARCHAR(32) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_openid_model (openid, model_id),
  INDEX idx_openid (openid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS purchases (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) NOT NULL,
  model_id VARCHAR(32) NOT NULL,
  price_cny DECIMAL(10,2) DEFAULT NULL,
  purchase_date DATE DEFAULT NULL,
  channel VARCHAR(100) DEFAULT NULL,
  note VARCHAR(500) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_openid_model (openid, model_id),
  INDEX idx_openid (openid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS series_meta (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(10) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL,
  short_name VARCHAR(10) NOT NULL,
  scale VARCHAR(20) NOT NULL,
  cover_image VARCHAR(500) NOT NULL,
  total_count INT UNSIGNED DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS models (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  series VARCHAR(10) NOT NULL,
  number INT UNSIGNED NOT NULL,
  name VARCHAR(200) NOT NULL,
  name_ja VARCHAR(200) NOT NULL,
  name_en VARCHAR(200) DEFAULT NULL,
  price INT UNSIGNED DEFAULT 0,
  price_tax_free INT UNSIGNED DEFAULT 0,
  release_date VARCHAR(20) DEFAULT NULL,
  is_limited TINYINT(1) DEFAULT 0,
  limited_type VARCHAR(20) DEFAULT NULL,
  image_url VARCHAR(500) NOT NULL,
  product_url VARCHAR(500) NOT NULL,
  tags JSON DEFAULT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_series (series)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS model_images (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  model_id VARCHAR(32) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  sort_order INT UNSIGNED DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_model_id (model_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
